/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import classes.Circulo;
import classes.Figura;
import classes.Retangulo;
import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author Pichau
 */
public class App extends javax.swing.JFrame {

    private Figura objFigura;

    public App() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTPFiguras = new javax.swing.JTabbedPane();
        jPCirculo = new javax.swing.JPanel();
        jLRaio = new javax.swing.JLabel();
        jTFRaio = new javax.swing.JTextField();
        jPRetangulo = new javax.swing.JPanel();
        jLBase = new javax.swing.JLabel();
        jLAltura = new javax.swing.JLabel();
        jTFBase = new javax.swing.JTextField();
        jTFAltura = new javax.swing.JTextField();
        jBCalcular = new javax.swing.JButton();
        jBSair = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTAResultado = new javax.swing.JTextArea();
        jBLimpar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLRaio.setText("Raio");

        jTFRaio.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                App.this.focusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                App.this.focusLost(evt);
            }
        });
        jTFRaio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                validaCampo(evt);
            }
        });

        javax.swing.GroupLayout jPCirculoLayout = new javax.swing.GroupLayout(jPCirculo);
        jPCirculo.setLayout(jPCirculoLayout);
        jPCirculoLayout.setHorizontalGroup(
            jPCirculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPCirculoLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLRaio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addComponent(jTFRaio, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );
        jPCirculoLayout.setVerticalGroup(
            jPCirculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPCirculoLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPCirculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLRaio)
                    .addComponent(jTFRaio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        jTPFiguras.addTab("Cículo", jPCirculo);

        jLBase.setText("Base");

        jLAltura.setText("Altura");

        jTFBase.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                App.this.focusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                App.this.focusLost(evt);
            }
        });
        jTFBase.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                validaCampo(evt);
            }
        });

        jTFAltura.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                App.this.focusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                App.this.focusLost(evt);
            }
        });
        jTFAltura.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                validaCampo(evt);
            }
        });

        javax.swing.GroupLayout jPRetanguloLayout = new javax.swing.GroupLayout(jPRetangulo);
        jPRetangulo.setLayout(jPRetanguloLayout);
        jPRetanguloLayout.setHorizontalGroup(
            jPRetanguloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPRetanguloLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPRetanguloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLBase)
                    .addComponent(jLAltura))
                .addGap(47, 47, 47)
                .addGroup(jPRetanguloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTFAltura, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE)
                    .addComponent(jTFBase))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        jPRetanguloLayout.setVerticalGroup(
            jPRetanguloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPRetanguloLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(jPRetanguloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLBase)
                    .addComponent(jTFBase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPRetanguloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLAltura)
                    .addComponent(jTFAltura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTPFiguras.addTab("Retângulo", jPRetangulo);

        jBCalcular.setText("Calcular");
        jBCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCalcularActionPerformed(evt);
            }
        });

        jBSair.setText("Sair");
        jBSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSairActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Resultado"));

        jTAResultado.setColumns(20);
        jTAResultado.setRows(5);
        jScrollPane1.setViewportView(jTAResultado);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(11, Short.MAX_VALUE))
        );

        jBLimpar.setText("Limpar");
        jBLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBLimparActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(16, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTPFiguras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jBCalcular)
                            .addComponent(jBSair)
                            .addComponent(jBLimpar))
                        .addGap(28, 28, 28))))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jBCalcular, jBLimpar, jBSair});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTPFiguras, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jBCalcular)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBLimpar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBSair, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jBCalcular, jBLimpar, jBSair});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCalcularActionPerformed
        if (jTPFiguras.getSelectedIndex() == 0) {
            if (jTFRaio.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Campo 'Raio' não foi preenchido", "Aviso", 0);
                jTFRaio.setText(null);
                jTFRaio.requestFocusInWindow();
                return;
            }
            double raio = Double.parseDouble(jTFRaio.getText());
            objFigura = new Circulo(raio);
        }
        if (jTPFiguras.getSelectedIndex() == 1) {
            if (jTFBase.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Campo 'Raio' não foi preenchido", "Aviso", 0);
                jTFBase.setText(null);
                jTFBase.requestFocusInWindow();
                return;
            }

            if (jTFAltura.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Campo 'Raio' não foi preenchido", "Aviso", 0);
                jTFAltura.setText(null);
                jTFAltura.requestFocusInWindow();
                return;
            }

            double base = Double.parseDouble(jTFBase.getText());
            double altura = Double.parseDouble(jTFAltura.getText());
            objFigura = new Retangulo(base, altura);
        } 
        jTAResultado.setText(objFigura.dados());
    }//GEN-LAST:event_jBCalcularActionPerformed

    private void jBSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jBSairActionPerformed

    private void jBLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBLimparActionPerformed
        jTFRaio.setText(null);
        jTFAltura.setText(null);
        jTFBase.setText(null);
    }//GEN-LAST:event_jBLimparActionPerformed

    private void validaCampo(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_validaCampo
        char tecla = evt.getKeyChar();
        if (!Character.isDigit(tecla) && tecla != '.') {
            this.getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_validaCampo

    private void focusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_focusGained
        if (evt.getSource() instanceof javax.swing.JTextField) {
            javax.swing.JTextField campo = (javax.swing.JTextField) evt.getSource();
            campo.setBackground(Color.LIGHT_GRAY);
        }
    }//GEN-LAST:event_focusGained

    private void focusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_focusLost
        if (evt.getSource() instanceof javax.swing.JTextField) {
            javax.swing.JTextField campo = (javax.swing.JTextField) evt.getSource();
            campo.setBackground(Color.WHITE);
        }
    }//GEN-LAST:event_focusLost

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new App().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBCalcular;
    private javax.swing.JButton jBLimpar;
    private javax.swing.JButton jBSair;
    private javax.swing.JLabel jLAltura;
    private javax.swing.JLabel jLBase;
    private javax.swing.JLabel jLRaio;
    private javax.swing.JPanel jPCirculo;
    private javax.swing.JPanel jPRetangulo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTAResultado;
    private javax.swing.JTextField jTFAltura;
    private javax.swing.JTextField jTFBase;
    private javax.swing.JTextField jTFRaio;
    private javax.swing.JTabbedPane jTPFiguras;
    // End of variables declaration//GEN-END:variables
}
